### ISSUE TITLE
download link has broken down

### ISSUE THREAD

**Issue by xiaobovlog** [zizhaozhang/nmi-wsi-diagnosis#2]
Dear authors, I want download the datasets of your experiment. But I can't download the datasets with your download link successfully. The error is "Too many requests.Sorry, this link has been automatically turned off for now. Learn more about traffic limits.". Could you please provide a new download link? Thank you very much!

**Comment by PingjunChen** [comment]
@xiaopeng940302 Thanks for your interests. I just tried downloading all the files, also got an error. However, I can download these files separately. I think the reason is the total storage of slide files exceeds some limit.  Those slides in the  "Slide/Img" folder may need to be downloaded one-by-one. 

If you cannot download separately, please give feedback.

**Comment by PingjunChen** [comment]
@xiaopeng940302 You may also consider using the script `download_nmi_wsi_data.sh` under `download` directory of the repo to download the dataset.

**Comment by xiaobovlog** [comment]
@PingjunChen Thank you for your help!
